/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_connectedway_io_FileWriter */

#ifndef _Included_com_connectedway_io_FileWriter
#define _Included_com_connectedway_io_FileWriter
#ifdef __cplusplus
extern "C" {
#endif
#undef com_connectedway_io_FileWriter_WRITE_BUFFER_SIZE
#define com_connectedway_io_FileWriter_WRITE_BUFFER_SIZE 1024L
#ifdef __cplusplus
}
#endif
#endif
