/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_connectedway_io_FileDescriptor */

#ifndef _Included_com_connectedway_io_FileDescriptor
#define _Included_com_connectedway_io_FileDescriptor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
