/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_connectedway_io_FileOutputStream */

#ifndef _Included_com_connectedway_io_FileOutputStream
#define _Included_com_connectedway_io_FileOutputStream
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
