/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_connectedway_io_RandomAccessFile */

#ifndef _Included_com_connectedway_io_RandomAccessFile
#define _Included_com_connectedway_io_RandomAccessFile
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
