/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_connectedway_io_Resolver */

#ifndef _Included_com_connectedway_io_Resolver
#define _Included_com_connectedway_io_Resolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_connectedway_io_Resolver
 * Method:    setResolverListener
 * Signature: (Lcom/connectedway/io/Resolver/ResolverListener;)V
 */
JNIEXPORT void JNICALL Java_com_connectedway_io_Resolver_setResolverListener
  (JNIEnv *, __attribute__((unused)) jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
