/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_connectedway_io_FileInputStream */

#ifndef _Included_com_connectedway_io_FileInputStream
#define _Included_com_connectedway_io_FileInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef com_connectedway_io_FileInputStream_MAX_SKIP_BUFFER_SIZE
#define com_connectedway_io_FileInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
